Isolate tasks in bootstrap.bat
WasatchPhotonics/ENLIGHTEN pull request #121
Opened 2023-04-05 14:57 UTC by samiebee43

Bring bootstrap debugging feature to mzeig-testing-4.0.6

2023-04-05 16:40 UTC, mzieg approved these changes
Changes makes sense.  My impression is that this will no longer have a "one-shot build installer" (equivalent to the old "installer" argument), but will rather require at least three invocations to match the old behavior (once with "rebuildall", then "pyinstaller", then "innosetup")?

2023-04-05 17:30 UTC, mzieg requested changes

2023-04-05 17:30 UTC, mzieg commented on scripts/bootstrap.bat
> +if "%install_python_deps%" == 1 (
I think this needs to be "1"

2023-04-05 17:30 UTC, mzieg commented on scripts/bootstrap.bat
> +if "%regenerate_qt" == 1 (
I think this needs to be "1"

2023-04-05 17:35 UTC, samiebee43 commented on scripts/bootstrap.bat
> +if "%install_python_deps%" == 1 (
it does

2023-04-05 17:37 UTC, samiebee43 commented
> Changes makes sense. My impression is that this will no longer have a "one-shot build installer" (equivalent to the old "installer" argument), but will rather require at least three invocations to match the old behavior (once with "rebuildall", then "pyinstaller", then "innosetup")?

Yes. I didn't include a one-shot, since that never worked on my end, but it can be trivially added

2023-04-05 17:49 UTC, mzieg requested changes

2023-04-05 17:49 UTC, mzieg commented on scripts/bootstrap.bat
> +if "%regenerate_qt" == "1" (
This needs to be %regenerate_qt% (closing marker)

2023-04-05 19:52 UTC, mzieg approved these changes

2023-04-12 13:58 UTC, samiebee43 commented
This PR and branch build-stage are no longer needed since #120 is up to date with sbee-build

2023-04-12 13:58 UTC, closed without merging